daangn/websites

_packages/@karrotmarket/prismic-config/schema/team_contents.json
team.daangn.com/src/__generated__/gatsby-introspection.json
team.daangn.com/src/__generated__/gatsby-plugin-documents.graphql
team.daangn.com/src/__generated__/gatsby-schema.graphql
team.daangn.com/src/__generated__/gatsby-types.d.ts
team.daangn.com/src/components/DetailLink.tsx
team.daangn.com/src/components/FaqAccordionItem.tsx
team.daangn.com/src/components/FormField.tsx
team.daangn.com/src/components/JobPostContentOrderedListSection.tsx
team.daangn.com/src/components/JobPostContentParagraphSection.tsx
team.daangn.com/src/components/JobPostContentUnorderedListSection.tsx
team.daangn.com/src/components/JobPostSummary.tsx
team.daangn.com/src/components/PageTitle.tsx
team.daangn.com/src/components/PrismicTeamContentsDataCultureBodyBenefit.tsx
team.daangn.com/src/components/PrismicTeamContentsDataCultureBodyHowWeWork.tsx
team.daangn.com/src/components/PrismicTeamContentsDataCultureBodyIllustrationAndDescription.tsx
team.daangn.com/src/components/PrismicTeamContentsDataCultureBodyKeyVisual.tsx
team.daangn.com/src/components/PrismicTeamContentsDataLifeBodyLifeContent.tsx
team.daangn.com/src/components/PrismicTeamContentsDataMainBodyKeyVisual.tsx
team.daangn.com/src/components/PrismicTeamContentsDataMainBodyTitleAndDescription.tsx
team.daangn.com/src/components/PrismicTeamContentsDataMainBodyTitleAndIllustration.tsx
team.daangn.com/src/components/PrismicTeamContentsDataMainBodyWideBanner.tsx
team.daangn.com/src/components/prismicTeamContentsDataMainBodyMemberQuoteCarousel/CarouselItem.tsx
team.daangn.com/src/gatsby-theme-stitches/stitches.config.ts
team.daangn.com/src/pages/index.tsx
team.daangn.com/src/pages/life.tsx

- Line height 적용
- life 페이지 content area 적용
- default layout variant 적용
- member quote 섹션 스타일 수정
- key visual 섹션 art-direction 적용
- wide banner 섹션 image constraint 수정

team.daangn.com: 짜잘한 수정사항들 반영

---

team.daangn.com/src/components/PrismicTeamContentsDataCultureBodyHowWeWork.tsx
team.daangn.com/src/components/PrismicTeamContentsDataCultureBodyKeyVisual.tsx

See https://daangn.slack.com/archives/C01TA45KWCV/p1623289232249700?thread_ts=1623118669.158300&cid=C01TA45KWCV

team.daangn.com: 디자인 피드백 반영

---

_packages/@karrotmarket/gatsby-transformer-job-post/gatsby/greenhouseJobCustomFieldParser.ts

- fix(team.daangn.com): Corparate 커스텀 필드 id 수정
- chore: 필드 파서 에러 메시지 개선

gatsby-transformer-job-post: 필드 파서 수정

---

_packages/@karrotmarket/gatsby-theme-prismic/gatsby/gatsby-config.ts
team.daangn.com/src/layouts/JobPostLayout.tsx
team.daangn.com/src/pages/culture.tsx
team.daangn.com/src/pages/culture/life.tsx
team.daangn.com/src/pages/index.tsx
team.daangn.com/src/templates/jobs.tsx

- chore(gatsby-theme-prismic): Imagix 파라미터 변경
- chore(team.daangn.com): OG 이미지 기본 퀄리티 조정

chore: Prismic 이미지 기본 퀄리티 조정

---

team.daangn.com/src/layouts/JobPostLayout.tsx
team.daangn.com/src/pages/culture.tsx
team.daangn.com/src/pages/culture/life.tsx
team.daangn.com/src/pages/index.tsx
team.daangn.com/src/templates/jobs.tsx

- chore(team.daangn.com): 흠 og image 를 png 로 바꿔볼까
- chore(team.daangn.com): 그냥 코드 스타일 정리
- chore(team.daangn.com): 빼먹은거
- fix(team.daangn.com): origin 잘못 쓴거 수정

team.daangn.com: OG 관련 짜잘한 수정

---

team.daangn.com/src/components/PrismicTeamContentsDataMainBodyMemberQuoteCarousel.tsx

And remove magic JS numbers using local-scoped tokens

fix(team.daangn.com): fit the carousel to full-width

---

README.md
_template/.gitignore
_template/gatsby/gatsby-config.ts
_template/gatsby/gatsby-node.ts
_template/package.json
_template/src/components/Greeting.tsx
_template/src/pages/404.tsx
_template/src/pages/index.tsx
_template/tsconfig.json
docs/add-new-site.md
docs/cloudflare-workers.md
docs/content-management.md
docs/content-preview.md
docs/google-tag-manager.md

- doc: update root README
- doc: add some initial docs (draft)

chore(docs): add initial docs

---

_packages/@karrotmarket/gatsby-transformer-job-post/gatsby/gatsby-node.ts
_packages/@karrotmarket/gatsby-transformer-job-post/gatsby/greenhouseJobCustomFieldParser.ts
team.daangn.com/src/__generated__/gatsby-introspection.json
team.daangn.com/src/__generated__/gatsby-plugin-documents.graphql
team.daangn.com/src/__generated__/gatsby-schema.graphql
team.daangn.com/src/__generated__/gatsby-types.d.ts
team.daangn.com/src/components/JobPostList.tsx
yarn.lock

Job Post 커스텀 필드 "Order" 값으로 정렬 우선순위를 부여할 수 있습니다. (내림 차순)

team.daangn.com: Greenhouse 커스텀 필드 기반 ordering 적용

---

_packages/@karrotmarket/gatsby-transformer-job-post/gatsby/gatsby-node.ts
_packages/@karrotmarket/gatsby-transformer-job-post/gatsby/greenhouseJobCustomFieldParser.ts
team.daangn.com/src/__generated__/gatsby-introspection.json
team.daangn.com/src/__generated__/gatsby-plugin-documents.graphql
team.daangn.com/src/__generated__/gatsby-schema.graphql
team.daangn.com/src/__generated__/gatsby-types.d.ts
team.daangn.com/src/components/JobPostSummary.tsx
team.daangn.com/src/gatsby-theme-stitches/stitches.config.ts

~~TODO:~~
~~호버 스타일이 따로 있어야 하지 않을까...?~~ -> DONE

team.daangn.com: 공고 목록 tags 필드를 UI에 추가

---

_packages/@karrotmarket/gatsby-transformer-job-post/gatsby/gatsby-node.ts
_packages/@karrotmarket/gatsby-transformer-job-post/gatsby/greenhouseJobCustomFieldParser.ts
team.daangn.com/src/components/JobPostSummary.tsx
team.daangn.com/src/components/JobPostingJsonLd.tsx
team.daangn.com/src/layouts/JobPostLayout.tsx
team.daangn.com/src/templates/jobs.tsx

- EmploymentType 에 `ASSISTANT` 타입추가
- jsonld  EmploymentType 매핑

feat: add ASSISTANT employment type

---

_packages/@karrotmarket/gatsby-transformer-job-post/gatsby/gatsby-node.ts
_packages/@karrotmarket/gatsby-transformer-job-post/gatsby/greenhouseJobCustomFieldParser.ts
team.daangn.com/gatsby/gatsby-config.ts
team.daangn.com/src/components/JobPostList.tsx
team.daangn.com/src/layouts/JobPostLayout.tsx

요거 주말전에 추가하면 좋을 것 같아서 작업해놔요.
@stump26 시간되실 때 천천히 사후 리뷰 부탁드릴게용

인턴십 외부 링크 추가

---

_packages/@karrotmarket/gatsby-theme-global-website/gatsby/gatsby-node.ts

`HOT_ARTICLE_API_SPECIAL_KEY` 값은 Gatsby Cloud 에서 주입해요

global: 추천 상품 API bot 차단 방지용 토큰추가

---

team.daangn.com/static/vercel.json

team.daangn.com: Vercel Redirect 파일 수동 배포

---

ads-local.daangn.com/src/components/organisms/LearnMore.tsx
ads-local.daangn.com/src/html.js
ads-local.daangn.com/src/pages/index.tsx

* Naver 사이트관리자 인증토큰 변경
* meta 태그 수정
* onClick 핸들러 포지션 수정

fix(advertisement): minor bug fix

---

_packages/@karrotmarket/gatsby-source-greenhouse-job-board/gatsby/gatsby-node.ts
team.daangn.com/gatsby/gatsby-config.ts

JobPost 까지는 트리거 안될까봐 불안하긴 한데 일단 이렇게 시도...

feat(team.daangn.com): re-enabled forceGC for Gatsby Cloud Build

---

_packages/@karrotmarket/gatsby-theme-team-website/gatsby/gatsby-node.ts
_packages/@karrotmarket/gatsby-theme-team-website/src/components/FormField.tsx
_packages/@karrotmarket/gatsby-theme-team-website/src/components/JobPostingJsonLd.tsx
_packages/@karrotmarket/gatsby-theme-team-website/src/components/formField/messages.ts
_packages/@karrotmarket/gatsby-theme-team-website/src/components/jobPostList/EmptyPlaceholder.tsx
_packages/@karrotmarket/gatsby-theme-team-website/src/components/jobPostList/emptyPlaceholder/messages.ts
_packages/@karrotmarket/gatsby-theme-team-website/src/pages/preview.tsx
_packages/@karrotmarket/gatsby-theme-team-website/src/templates/JobApplicationPage.tsx
_packages/@karrotmarket/gatsby-theme-team-website/src/templates/JobPostPage.tsx
_packages/@karrotmarket/gatsby-theme-team-website/src/templates/JobsPage.tsx
_packages/@karrotmarket/gatsby-theme-team-website/src/templates/jobApplicationPage/messages.ts
_packages/@karrotmarket/gatsby-theme-team-website/src/templates/jobPostPage/messages.ts
_packages/@karrotmarket/gatsby-theme-team-website/src/templates/jobsPage/messages.ts
_packages/@karrotmarket/gatsby-theme-team-website/tsconfig.json
team.daangn.com/src/@karrotmarket/gatsby-theme-team-website/components/jobPostList/emptyPlaceholder/messages.ts
team.daangn.com/src/@karrotmarket/gatsby-theme-team-website/templates/jobApplicationPage/messages.ts
team.daangn.com/src/@karrotmarket/gatsby-theme-team-website/templates/jobPostPage/messages.ts
team.daangn.com/src/@karrotmarket/gatsby-theme-team-website/templates/jobsPage/messages.ts

Prismic Content/Custom Question 등에서 개선할 부분 제외

gatsby-theme-team-website: UI 메시지 i18n 메시지 적용

---

_packages/@karrotmarket/gatsby-theme-team-website/src/templates/JobApplicationPage.tsx

Revert "faet: disable alternative_civilian, veterans ,disability fields"

---

www.daangnpay.com/src/components/Footer.tsx
www.daangnpay.com/src/components/Header.tsx
www.daangnpay.com/src/components/HeroSection.tsx
www.daangnpay.com/src/components/TitleAndIllustration.tsx
www.daangnpay.com/src/components/WideBanner.tsx
www.daangnpay.com/src/pages/index.tsx

- stitches 교체: gatsby-theme-stitches에서 @karrotmarket/gatsby-theme-global-website
- prismic source type 수정

www.daangnpay.com: fix prismic source type

---

ads-local.daangn.com/src/components/organisms/DownloadBtnMobile.tsx

chore(ads-local): change download url

---

_packages/@karrotmarket/gatsby-theme-team-website/src/layouts/DefaultLayout.tsx
_packages/@karrotmarket/gatsby-theme-team-website/src/layouts/JobPostLayout.tsx
_packages/@karrotmarket/gatsby-theme-team-website/src/pages/404.tsx
_packages/@karrotmarket/gatsby-theme-team-website/src/pages/completed.tsx
_packages/@karrotmarket/gatsby-theme-team-website/src/pages/index.tsx
_packages/@karrotmarket/gatsby-theme-team-website/src/pages/preview.tsx
_packages/@karrotmarket/gatsby-theme-team-website/src/templates/CulturePage.tsx
_packages/@karrotmarket/gatsby-theme-team-website/src/templates/FaqPage.tsx
_packages/@karrotmarket/gatsby-theme-team-website/src/templates/JobsPage.tsx
_packages/@karrotmarket/gatsby-theme-team-website/src/templates/LifePage.tsx
_packages/@karrotmarket/gatsby-theme-team-website/src/templates/PrismicTeamsArticlePage.tsx

전: 직군 필터 변경하면 맨 위로 감 (배너 높이 때문에 확 올라감)
후: main 으로 skip navigation
영상 첨부: https://twitter.com/KrComet/status/1466775813882540035

공고 필터 변경 시 main 위치로 스킵 네비게이션 지원

---

careers.ca.karrotmarket.com/gatsby/gatsby-config.ts
careers.jp.karrotmarket.com/gatsby/gatsby-config.ts

Fixed [WMAS-17]
[WMAS-17]: https://karrot.atlassian.net/browse/WMAS-17?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ca, jp 채용사이트 제출 후 페이지 CORS 허용

---

ads-local.daangn.com/src/components/organisms/LearnMore.tsx

ads-local-refactor 과는 별개로 광고주향으로 나가는 가이드 링크들만 우선 업데이트가 필요해서 수정했어요.

fix(ads-local): 2/23 지역광고2.0 업데이트 관련 FAQ 링크 수정반영

---

_packages/@karrotmarket/gatsby-theme-team-website/src/components/JobPostSummary.tsx

fix(team.daangn.com): jobs list container overflow

---

_packages/@karrotmarket/gatsby-theme-global-website/src/@karrotmarket/gatsby-theme-website/components/header/NavigationListItem.tsx
_packages/@karrotmarket/gatsby-theme-global-website/src/pages/index.tsx
ca.karrotmarket.com/src/@karrotmarket/gatsby-theme-global-website/components/Layout.tsx
uk.karrotmarket.com/src/@karrotmarket/gatsby-theme-global-website/components/Layout.tsx
us.karrotmarket.com/src/@karrotmarket/gatsby-theme-global-website/components/Layout.tsx

fix: global navbar visible

---

jp.karrotmarket.com/package.json
jp.karrotmarket.com/src/@karrotmarket/gatsby-theme-global-website/styles/global.ts
jp.karrotmarket.com/src/__generated__/gatsby-schema.graphql
jp.karrotmarket.com/src/__generated__/gatsby-types.d.ts
yarn.lock

stylesheet이 주입이 안되서 상단 네비게이션바 색이 안나오는 이슈 수정했어요~
jp만 쉐도잉해서 쓰다보니 불편한 감이 있네요.. 수정해야겠네용

fix(jp.karrotmarket.com): navbar visible

---

_workers/greenhouse-proxy-worker/package.json
_workers/greenhouse-proxy-worker/src/worker.ts
_workers/greenhouse-proxy-worker/wrangler.toml
yarn.lock

greenhouse-proxy-worker: migrate to wrangler 2

---

_packages/@karrotmarket/gatsby-theme-team-website/src/templates/JobApplicationPage.tsx

Fixed [WMAS-76]
[WMAS-76]: https://karrot.atlassian.net/browse/WMAS-76?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WMAS-76] 지원 페이지 누락된 Head 추가

---

_packages/@karrotmarket/gatsby-theme-global-website/gatsby/gatsby-node.ts
_packages/@karrotmarket/gatsby-theme-global-website/src/components/about/SubtitleAndLinks.tsx
_packages/@karrotmarket/gatsby-theme-global-website/src/pages/about.tsx
_packages/@karrotmarket/gatsby-theme-global-website/src/pages/index.tsx

See [WMAS-86]
[WMAS-86]: https://karrot.atlassian.net/browse/WMAS-86?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WMAS-86] 통화/날짜 형식 지역화

---

_packages/@karrotmarket/gatsby-theme-team-website/src/templates/JobPostPage.tsx

Resolved [WMAS-51]
[WMAS-51]: https://karrot.atlassian.net/browse/WMAS-51?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WMAS-51] respect FAQ page feature toggle

---

_packages/@karrotmarket/gatsby-theme-team-website/src/layouts/DefaultLayout.tsx
_packages/@karrotmarket/gatsby-theme-team-website/src/layouts/JobPostLayout.tsx
_packages/@karrotmarket/gatsby-theme-team-website/src/layouts/jobPostLayout/JobPostingJsonLd.tsx
_packages/@karrotmarket/gatsby-theme-team-website/src/templates/JobPostPage.tsx
_packages/@karrotmarket/gatsby-theme-team-website/src/utils/common.ts

Resolved [WMAS-56]
[WMAS-56]: https://karrot.atlassian.net/browse/WMAS-56?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WMAS-56] Fix page title

---

_packages/@karrotmarket/gatsby-theme-website-team/gatsby/gatsby-config.ts
_packages/@karrotmarket/gatsby-theme-website-team/package.json
_packages/@karrotmarket/gatsby-theme-website-team/src/templates/JobApplicationPage.tsx
_workers/greenhouse-proxy-worker/src/worker.ts
yarn.lock

Turnstile integration

---

_packages/@karrotmarket/gatsby-theme-website-team/gatsby/gatsby-config.ts
_packages/@karrotmarket/gatsby-theme-website-team/package.json
team.daangn.com/gatsby-node.ts
team.daangn.com/src/templates/IrPage.tsx
yarn.lock

See https://github.com/gatsbyjs/gatsby/issues/35636
Resolves [WMAS-46]
[WMAS-46]: https://karrot.atlassian.net/browse/WMAS-46?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WMAS-46] remove temporal patch code for file downloading

---

_packages/@karrotmarket/gatsby-theme-website-global/src/components/phoneMockup/PhoneMockupHome.tsx
_packages/@karrotmarket/gatsby-theme-website-global/src/components/phoneMockup/phoneMockupHome/Articles.tsx
_packages/@karrotmarket/gatsby-theme-website-global/src/components/phoneMockup/phoneMockupHome/Filters.tsx

Resolves [WMAS-100]
[WMAS-100]: https://karrot.atlassian.net/browse/WMAS-100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WMAS-100] PhoneMockupHome 애니메이션 제거

---

_packages/@karrotmarket/gatsby-theme-website-team/src/templates/FaqPage.tsx

- 모바일 환경에서 자주 묻는 질문 그룹 텍스트와 스크롤바가 겹치는 문제 수정

Update FaqGroup style

---

about.daangn.com/src/components/blog/FeaturedPost.tsx
about.daangn.com/src/components/blog/Navigation.tsx
about.daangn.com/src/pages/service.tsx

- featured post에 링크 추가
- search input 비활성화(임시)
- 폰트 스타일 수정

about 페이지 수정

---

about.daangn.com/src/pages/service.tsx

refactor: update content

---

_packages/@karrotmarket/gatsby-theme-post/gatsby/gatsby-config.ts
_packages/@karrotmarket/gatsby-theme-website-global/src/@karrotmarket/gatsby-theme-website/components/footer/FooterEntryItem.tsx
_packages/@karrotmarket/gatsby-theme-website/src/components/Footer.tsx
_packages/@karrotmarket/gatsby-theme-website/src/components/footer/FooterEntryItem.tsx
about.daangn.com/src/pages/service.tsx

- footer entry items: text에서 html로 변경(볼드 처리 위해)

refactor: replace plain text to html for footer item

---

jp.karrotmarket.com/gatsby-config.ts
jp.karrotmarket.com/package.json
jp.karrotmarket.com/src/components/FeaturedPost.tsx
jp.karrotmarket.com/src/components/PostCard.tsx
jp.karrotmarket.com/src/components/PostList.tsx
jp.karrotmarket.com/src/pages/blog.tsx
yarn.lock

feat: jp blog page

---

jp.karrotmarket.com/src/components/PostList.tsx

- featured post에 최신글, 포스트 리스트 영역은 featured post 제외하도록 수정

feat: apply requirement

---

team.daangn.com/gatsby-browser.tsx

- about.daang.com 표준 URL 설정
- team.daangn.com에서 about.daangn.com으로 redirection 설정 추가

feat: add redirection for canonical url

---

about.daangn.com/src/components/blogPostPage/PostBodyRichText.tsx

refactor: post body style

---

about.daangn.com/src/components/blogPostPage/PostBodyCtaButton.tsx

refactor: post body cta button style

---

_packages/@karrotmarket/gatsby-theme-website-team/src/pages/index.tsx
_packages/@karrotmarket/gatsby-theme-website-team/src/templates/CulturePage.tsx
_packages/@karrotmarket/gatsby-theme-website-team/src/templates/FaqPage.tsx
_packages/@karrotmarket/gatsby-theme-website-team/src/templates/JobApplicationPage.tsx
_packages/@karrotmarket/gatsby-theme-website-team/src/templates/JobPostPage.tsx
_packages/@karrotmarket/gatsby-theme-website-team/src/templates/JobsPage.tsx
_packages/@karrotmarket/gatsby-theme-website-team/src/templates/LifePage.tsx
_packages/@karrotmarket/gatsby-theme-website-team/src/templates/PrismicTeamsArticlePage.tsx
_packages/@karrotmarket/gatsby-theme-website-team/src/utils/common.ts
team.daangn.com/gatsby-browser.tsx
team.daangn.com/src/pages/ir.tsx
team.daangn.com/src/templates/FinancialStatementsPage.tsx
team.daangn.com/src/templates/IrPage.tsx

- meta refresh로 리디렉션 수정
- [문서](https://developers.google.com/search/docs/crawling-indexing/301-redirects?hl=ko#metarefresh)

refactor: add redirection using meta refresh

---

_packages/@karrotmarket/gatsby-theme-website-team/src/utils/common.ts

update: add ignore case

---

_packages/@karrotmarket/gatsby-theme-website-team/src/components/JobPostSummary.tsx

update: tag style on job post list

---

about.daangn.com/src/components/blogPostPage/PostBodyRichText.tsx

refactor: update post text style

---

_packages/@karrotmarket/gatsby-transformer-post/gatsby/gatsby-node.ts
_packages/@karrotmarket/gatsby-transformer-post/gatsby/types.ts
about.daangn.com/src/components/blogPostPage/PostBodySingleImage.tsx
about.daangn.com/src/templates/BlogPostPage.tsx

- 포스트 모델에 single image section 재생성
- gatsby-transformer-post 스키마 추가
- 컴포넌트 추가

feat: add single image section slice

---

_packages/@karrotmarket/gatsby-theme-website-global/src/components/home/HeroSection.tsx
_packages/@karrotmarket/gatsby-transformer-post/gatsby/gatsby-node.ts
_packages/@karrotmarket/gatsby-transformer-post/gatsby/types.ts
about.daangn.com/src/components/blogPostPage/PostBodyDivider.tsx
about.daangn.com/src/components/blogPostPage/PostBodyQuote.tsx
about.daangn.com/src/components/blogPostPage/Tag.tsx
about.daangn.com/src/components/blogPostPage/TagList.tsx
about.daangn.com/src/templates/BlogPostPage.tsx

- 포스트 divider 슬라이스 추가
- 임시 스타일 적용

feat: add divider slice

---

about.daangn.com/src/components/blogPostPage/DotDivider.tsx
about.daangn.com/src/components/blogPostPage/PostBodyCtaButton.tsx
about.daangn.com/src/components/blogPostPage/PostBodyDivider.tsx
about.daangn.com/src/templates/BlogPostPage.tsx

- divider dot type svg로 대체(safari 지원)
- 반응형 적용

refactor: update styles

---

about.daangn.com/src/components/pr/PrCard.tsx

- pr list style 수정 : 사이즈, text overflow 처리

refactor: pr list style

---

about.daangn.com/package.json
about.daangn.com/src/components/pr/PrCard.tsx
about.daangn.com/src/components/prPostPage/PrPostBodyRichText.tsx
about.daangn.com/src/pages/company/pr.tsx
about.daangn.com/src/templates/PrPostPage.tsx
yarn.lock

refactor: update pr page

---

_packages/@karrotmarket/gatsby-theme-brochure/package.json
_packages/@karrotmarket/gatsby-theme-post/package.json
_packages/@karrotmarket/gatsby-theme-website-global/package.json
_packages/@karrotmarket/gatsby-theme-website-team/package.json
_packages/@karrotmarket/gatsby-transformer-note-post/package.json
_packages/@karrotmarket/gatsby-transformer-post/gatsby/gatsby-node.ts
_packages/@karrotmarket/gatsby-transformer-post/gatsby/types.ts
_workers/prismic-if-note-com/package.json
about.daangn.com/src/components/prPostPage/PrPostBodyRichText.tsx
about.daangn.com/src/components/prPostPage/PrPostBodySummaryBulletSection.tsx
about.daangn.com/src/templates/PrPostPage.tsx
ads-local.daangn.com/package.json
yarn.lock

- 보도자료 상단 요약(bullet 스타일)영역 추가
- 패키지 버전업
- gatsby-plugin-head-seo
- note-com-js
- gatsby-source-note-com

feat: add slice for pr post

---

about.daangn.com/src/components/blogPostPage/RelatedPost.tsx
about.daangn.com/src/templates/BlogPostPage.tsx

feat: add related post

---

_packages/@karrotmarket/gatsby-transformer-post/gatsby/gatsby-node.ts
_packages/@karrotmarket/gatsby-transformer-post/gatsby/types.ts
about.daangn.com/src/components/blogPostPage/Author.tsx

- Prismic 멤버 프로필에 개인 프로필 링크를 추가할 수 있어요

멤버 프로필 개인 프로필 링크 추가

---

_packages/@karrotmarket/gatsby-theme-website-team/src/components/JobPostContentSection.tsx

style: remove gap

---

about.daangn.com/src/@karrotmarket/gatsby-theme-website-team/components/jobPostSummary/generateProperties.ts
about.daangn.com/src/@karrotmarket/gatsby-theme-website-team/layouts/jobPostLayout/generateProperties.ts
careers.ca.karrotmarket.com/src/@karrotmarket/gatsby-theme-website-team/layouts/jobPostLayout/generateProperties.ts
careers.jp.karrotmarket.com/src/@karrotmarket/gatsby-theme-website-team/layouts/jobPostLayout/generateProperties.ts
team.daangn.com/src/@karrotmarket/gatsby-theme-website-team/components/jobPostSummary/generateProperties.ts
team.daangn.com/src/@karrotmarket/gatsby-theme-website-team/layouts/jobPostLayout/generateProperties.ts

feat: add property

---

_packages/@karrotmarket/gatsby-theme-seed-design/src/Icon.tsx
_packages/@karrotmarket/gatsby-theme-website-team/src/templates/JobsPage.tsx

- 채용 페이지에서 icon을 눌렀을때 select가 활성화되지 않는 문제를 수정합니다.

fix(about.daangn.com): add pointer event to svg icon

---

about.daangn.com/src/pages/ir.tsx
about.daangn.com/src/templates/IrPage.tsx

- IR 공고 게시의 게시일을 삭제했습니다.
https://daangn.slack.com/archives/C04U09CTAH0/p1716356326031699

feat(about.daangn.com): remove publication date

---

.github/workflows/deploy-about-daangn-com-production.yml
.github/workflows/deploy-about-daangn-com.yml
_workers/about-daangn-com-production/.gitignore
_workers/about-daangn-com-production/functions/_middleware.ts
_workers/about-daangn-com-production/functions/env.d.ts
_workers/about-daangn-com-production/functions/serve.ts
_workers/about-daangn-com-production/package.json
_workers/about-daangn-com-production/public/_headers
_workers/about-daangn-com-production/public/robots.txt
_workers/about-daangn-com-production/tsconfig.json
_workers/about-daangn-com-production/wrangler.toml
yarn.lock

Reverts daangn/websites#1013
DNS 옮기는거 깜빡했다 ㅎㅎ;

Revert "about.daangn.com: 구 배포 리소스 제거"
